"""
The logic behind the Hassad app -- deliberately free of any Streamlit code.

Why split it out: the app's brain can then be tested from a plain Python
script (see the self-test at the bottom), and a teammate can change the look
of the app without touching the calculations. Everything here reuses the
verified modules: parse -> graph -> simulate -> exact.

Two things this module knows that the solver modules don't:
  * LANGUAGE -- every farmer-facing sentence exists in English and Arabic
    (templates in TEMPLATES below; the app's UI strings live in i18n.py).
  * ANY FARM -- fields can be the 11 traced Bekaa fields OR polygons a farmer
    drew on the map (custom_fields_from_geojson). All functions take an
    explicit `fields` list so both cases run through the same pipeline.
"""

from functools import lru_cache
import html

import networkx as nx
from shapely.geometry import Point, Polygon

from parse import Field, load_fields, make_projector
from graph import build_adjacency_graph, distance_matrix_km
from simulate import simulate_season, largest_standing_block, harvest_days
from exact import exact_fire_only, exact_weighted, reoptimize
from optimize import naive_largest_first, greedy_fire_only

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------

# The two adjacency rules the satellite check showed BOTH occur, depending on
# the year (cured gaps in 2025 -> 175 m; green gaps in 2024/2026 -> 100 m).
GAP_RULES = {
    "175 m — gaps are cured fuel (a dry year, like June 2025)": 175.0,
    "100 m — gaps stay green (a wet year, like June 2024)": 100.0,
}
DEFAULT_GAP_RULE = list(GAP_RULES)[0]

# Weight on driving distance when the farmer asks for the balanced plan.
TRAVEL_WEIGHT = 5.0

# ECONOMICS -- assumptions, clearly labelled as such until Team A sources them.
# Bekaa irrigated wheat commonly yields 3-4 t/ha; world wheat trades roughly
# $200-300/t. We show "value at stake", never "money saved": we have no
# ignition probability, and a judge would ask.
WHEAT_YIELD_T_PER_HA = 3.5        # ASSUMED -- replace with a sourced Bekaa figure
WHEAT_PRICE_USD_PER_T = 250.0     # ASSUMED -- replace with the current market price
FARMER_COST_USD = 0.0             # this one is a fact

# Names for fields a farmer draws: 1, 2, 3 ... (rendered per language).
CUSTOM_FIELD_NAMES = [str(i) for i in range(1, 100)]


# ---------------------------------------------------------------------------
# LANGUAGE TEMPLATES (farmer-facing sentences generated by the logic)
# ---------------------------------------------------------------------------

TEMPLATES = {
    "en": {
        "day_one": "{d}",
        "day_range": "{a}–{b}",
        "why_bridge": ("Field {f} is the bridge inside the largest block of dry wheat "
                       "({before} ha). Cutting it splits that block into {sizes} ha pieces."),
        "why_shrink": ("Field {f} ({area} ha) is part of the largest block ({before} ha); "
                       "cutting it shrinks that block to {after} ha."),
        "why_lower": ("Cutting field {f} lowers the largest standing block from "
                      "{before} ha to {after} ha."),
        "why_elsewhere": ("The largest block ({before} ha) is elsewhere; field {f} "
                          "({area} ha) is the cheapest safe cut right now and keeps the "
                          "harvester moving efficiently."),
        "wa_title": "Hassad harvest plan",
        "wa_cut": "Already cut: {list}",
        "wa_line": "Day {day}: field {f}",
        "wa_footer": "Cut in this order. Each cut field protects the ones next to it.",
        "cal_title": "Hassad harvest calendar",
        "cal_sub": ("Cut the fields in this order. Each day shows the largest block of "
                    "standing dry wheat left afterwards — smaller is safer."),
        "cal_head": ["Day", "Field", "Size", "Largest block left", "Why"],
        "ha": "ha",
        "dir": "ltr",
    },
    "ar": {
        "day_one": "{d}",
        "day_range": "{a}–{b}",
        "why_bridge": ("حقل {f} هو الجسر داخل أكبر كتلة قمح جاف ({before} هكتار). "
                       "حصاده يقسّمها إلى قطع بمساحة {sizes} هكتار."),
        "why_shrink": ("حقل {f} ({area} هكتار) جزء من أكبر كتلة ({before} هكتار)؛ "
                       "حصاده يصغّرها إلى {after} هكتار."),
        "why_lower": ("حصاد حقل {f} يخفّض أكبر كتلة قائمة من {before} إلى {after} هكتار."),
        "why_elsewhere": ("أكبر كتلة ({before} هكتار) في مكان آخر؛ حقل {f} ({area} هكتار) "
                          "هو الحصاد الآمن الأسهل الآن ويُبقي الحصّادة تعمل بكفاءة."),
        "wa_title": "خطة الحصاد — حصاد",
        "wa_cut": "تم حصاده: {list}",
        "wa_line": "اليوم {day}: حقل {f}",
        "wa_footer": "احصدوا بهذا الترتيب. كل حقل محصود يحمي الحقول المجاورة له.",
        "cal_title": "تقويم الحصاد — حصاد",
        "cal_sub": ("احصدوا الحقول بهذا الترتيب. كل يوم يُظهر أكبر كتلة قمح جاف "
                    "تبقى قائمة بعده — الأصغر أكثر أماناً."),
        "cal_head": ["اليوم", "الحقل", "المساحة", "أكبر كتلة متبقية", "السبب"],
        "ha": "هكتار",
        "dir": "rtl",
    },
}


def tpl(lang):
    return TEMPLATES.get(lang, TEMPLATES["en"])


# ---------------------------------------------------------------------------
# FIELDS: the traced Bekaa set, or a farm the farmer drew
# ---------------------------------------------------------------------------

@lru_cache(maxsize=1)
def all_fields():
    """The 11 traced Bekaa fields, loaded once."""
    return tuple(load_fields(verbose=False))


def field_names(fields=None):
    return [f.name for f in (fields if fields is not None else all_fields())]


def custom_fields_from_geojson(drawings):
    """
    Turn polygons drawn on the map (GeoJSON features from the Draw tool)
    into Field objects the whole pipeline understands.

    Each drawing becomes a field named 1, 2, 3... in drawing order. Tiny or
    invalid shapes (a mis-tap) are ignored. Returns a list of Field.
    """
    polys = []
    for feat in drawings or []:
        geom = (feat or {}).get("geometry") or {}
        if geom.get("type") != "Polygon" or not geom.get("coordinates"):
            continue
        ring = [(float(x), float(y)) for x, y, *_ in geom["coordinates"][0]]
        if len(ring) < 4:
            continue
        p = Polygon(ring)
        if not p.is_valid:
            p = p.buffer(0)
        if p.is_empty:
            continue
        polys.append(p)
    if not polys:
        return []

    ref_lon = sum(p.centroid.x for p in polys) / len(polys)
    ref_lat = sum(p.centroid.y for p in polys) / len(polys)
    project = make_projector(ref_lon, ref_lat)

    fields = []
    for name, p_ll in zip(CUSTOM_FIELD_NAMES, polys):
        p_m = Polygon([project(lon, lat) for lon, lat in p_ll.exterior.coords])
        if not p_m.is_valid:
            p_m = p_m.buffer(0)
        area_ha = p_m.area / 10_000.0
        if area_ha < 0.05:                   # smaller than a garden: a mis-tap
            continue
        c = p_m.centroid
        fields.append(Field(name=name, poly_m=p_m, poly_ll=p_ll,
                            area_ha=area_ha, cx=c.x, cy=c.y))
    return fields


def build_world(selected, threshold_m, fields=None):
    """Graph + distance matrix for just the fields the farmer selected."""
    pool = fields if fields is not None else all_fields()
    chosen = [f for f in pool if f.name in set(selected)]
    if not chosen:
        raise ValueError("select at least one field")
    G = build_adjacency_graph(chosen, threshold_m=threshold_m)
    matrix, index = distance_matrix_km(chosen)
    return chosen, G, matrix, index


# ---------------------------------------------------------------------------
# EXPLAINING EACH DAY -- "why this field today?"
# ---------------------------------------------------------------------------

def _component_sizes(G, standing):
    if not standing:
        return []
    sub = G.subgraph(standing)
    return sorted(
        (sum(G.nodes[n]["area_ha"] for n in comp) for comp in nx.connected_components(sub)),
        reverse=True,
    )


def why_sentence(G, standing_before, field, lang="en"):
    """
    One plain sentence justifying a cut, derived from the fire graph itself.
    Deterministic and template-based: nothing here can hallucinate.
    """
    t = tpl(lang)
    block_before, ha_before = largest_standing_block(G, standing_before)
    standing_after = set(standing_before) - {field}
    _, ha_after = largest_standing_block(G, standing_after)
    area = G.nodes[field]["area_ha"]
    args = dict(f=field, area=f"{area:.1f}", before=f"{ha_before:.0f}", after=f"{ha_after:.0f}")

    if field in block_before:
        pieces = _component_sizes(G, block_before - {field})
        if len(pieces) >= 2:
            args["sizes"] = " + ".join(f"{p:.0f}" for p in pieces[:3])
            return t["why_bridge"].format(**args)
        return t["why_shrink"].format(**args)
    if ha_after < ha_before - 1e-9:
        return t["why_lower"].format(**args)
    return t["why_elsewhere"].format(**args)


def day_label(day, d, lang="en"):
    t = tpl(lang)
    return t["day_one"].format(d=day) if d == 1 else t["day_range"].format(a=day, b=day + d - 1)


def schedule_rows(G, order, first_day=1, harvested_before=(), lang="en"):
    """Turn an order into day-by-day rows with the largest-block numbers and a
    plain-language reason for each field."""
    standing = set(G.nodes) - set(harvested_before)
    rows, day = [], first_day
    for field in order:
        d = harvest_days(G.nodes[field]["area_ha"])
        _, ha_before = largest_standing_block(G, standing)
        reason = why_sentence(G, standing, field, lang)
        standing = standing - {field}
        _, ha_after = largest_standing_block(G, standing)
        rows.append({
            "Day": day_label(day, d, lang),
            "Field": field,
            "Hectares": round(G.nodes[field]["area_ha"], 1),
            "Days": d,
            "Largest block before (ha)": round(ha_before, 1),
            "Largest block after (ha)": round(ha_after, 1),
            "Why this field now": reason,
        })
        day += d
    return rows


# ---------------------------------------------------------------------------
# THE TWO OPERATIONS THE APP EXPOSES
# ---------------------------------------------------------------------------

def plan(selected, gap_rule=DEFAULT_GAP_RULE, balanced=False, fields=None, lang="en"):
    """One-tap plan: the provably best order for the selected fields."""
    threshold = GAP_RULES[gap_rule]
    chosen, G, matrix, index = build_world(selected, threshold, fields)

    if balanced:
        _, order = exact_weighted(G, matrix, index, w1=1.0, w2=TRAVEL_WEIGHT)
    else:
        _, order = exact_fire_only(G)

    optimal = simulate_season(order, G, matrix, index, label="Hassad (optimal)")
    naive = simulate_season(naive_largest_first(G), G, matrix, index,
                            label="largest field first")
    greedy = simulate_season(greedy_fire_only(G), G, matrix, index, label="greedy")
    pct = ((naive.fire_risk_score - optimal.fire_risk_score) / naive.fire_risk_score * 100
           if naive.fire_risk_score else 0.0)

    return {
        "fields": chosen, "G": G, "matrix": matrix, "index": index,
        "threshold": threshold, "balanced": balanced, "lang": lang,
        "order": order,
        "optimal": optimal, "naive": naive, "greedy": greedy,
        "pct_vs_naive": pct,
        "rows": schedule_rows(G, order, lang=lang),
        "harvested": [], "position": None, "done": False,
    }


def replan(previous, harvested, position=None, lang=None):
    """Mid-season update: the farmer marks what is already cut (in any order)
    and where the machine is; we re-solve the rest of the season."""
    lang = lang or previous.get("lang", "en")
    G, matrix, index = previous["G"], previous["matrix"], previous["index"]
    harvested = [h for h in harvested if h in G.nodes]
    w2 = TRAVEL_WEIGHT if previous["balanced"] else 0.0
    if position not in index:
        position = None
    result = reoptimize(G, matrix, index, harvested=harvested, position=position,
                        w1=1.0, w2=w2)
    remaining = set(G.nodes) - set(harvested)
    first_day = 1 + sum(harvest_days(G.nodes[h]["area_ha"]) for h in harvested)

    out = dict(previous)
    out.update({
        "order": result["order"], "lang": lang,
        "harvested": list(harvested), "position": position,
        "rows": schedule_rows(G, result["order"], first_day=first_day,
                              harvested_before=harvested, lang=lang),
        "remaining_fire_risk": result["fire_risk"],
        "remaining_travel_km": result["travel_km"],
        "done": not remaining,
    })
    if remaining and result["order"]:
        H = G.subgraph(remaining).copy()
        out["optimal"] = simulate_season(result["order"], H, matrix, index,
                                         label="Hassad (re-optimized)")
        out["naive"] = simulate_season(naive_largest_first(H), H, matrix, index,
                                       label="largest field first")
        out["greedy"] = simulate_season(greedy_fire_only(H), H, matrix, index,
                                        label="greedy")
        n, o = out["naive"].fire_risk_score, out["optimal"].fire_risk_score
        out["pct_vs_naive"] = (n - o) / n * 100 if n else 0.0
    return out


def relabel(plan_dict, lang):
    """Re-generate the farmer-facing sentences in another language without
    re-solving anything (the order and numbers do not depend on language)."""
    G = plan_dict["G"]
    harvested = plan_dict.get("harvested", [])
    first_day = 1 + sum(harvest_days(G.nodes[h]["area_ha"]) for h in harvested)
    out = dict(plan_dict)
    out["lang"] = lang
    out["rows"] = schedule_rows(G, plan_dict["order"], first_day=first_day,
                                harvested_before=harvested, lang=lang)
    return out


# ---------------------------------------------------------------------------
# ECONOMICS
# ---------------------------------------------------------------------------

def economics(plan_dict):
    """
    Value at stake for the fields in the plan, the farmer's cost, and the
    honest version of "how much does this save?":

    We cannot claim money saved per season without an ignition probability,
    which nobody has measured. What the model DOES give exactly is the size of
    the burnable block a fire would find on a random day of the season -- the
    season-average largest connected block -- under the usual order versus
    this plan. The difference is hectares (and dollars) of crop that are no
    longer exposed PER FIRE EVENT. Multiply by whatever chance of a fire you
    believe in (the app exposes that as a slider) to get an expected saving.
    """
    G = plan_dict["G"]
    total_ha = sum(G.nodes[n]["area_ha"] for n in G.nodes)
    value_per_ha = WHEAT_YIELD_T_PER_HA * WHEAT_PRICE_USD_PER_T
    naive, opt = plan_dict.get("naive"), plan_dict.get("optimal")
    mean_naive = (naive.fire_risk_score / naive.season_days
                  if naive is not None and naive.season_days else 0.0)
    mean_plan = (opt.fire_risk_score / opt.season_days
                 if opt is not None and opt.season_days else 0.0)
    delta_ha = max(mean_naive - mean_plan, 0.0)
    return {
        "total_ha": total_ha,
        "value_usd": total_ha * value_per_ha,
        "value_per_ha_usd": value_per_ha,
        "farmer_cost_usd": FARMER_COST_USD,
        "yield_t_per_ha": WHEAT_YIELD_T_PER_HA,
        "price_usd_per_t": WHEAT_PRICE_USD_PER_T,
        "exposure_reduction_pct": plan_dict.get("pct_vs_naive", 0.0),
        "mean_block_naive_ha": mean_naive,
        "mean_block_plan_ha": mean_plan,
        "delta_ha_per_event": delta_ha,
        "delta_usd_per_event": delta_ha * value_per_ha,
    }


def expected_saving_usd(econ, chance_pct):
    """Expected saving per season = chance a fire reaches the fields x value
    no longer exposed per event. The chance is the user's assumption."""
    return econ["delta_usd_per_event"] * chance_pct / 100.0


# Which crops the same model applies to. Hassad needs two things of a crop:
# it must be FUEL while standing dry, and its harvest must remove that fuel.
# Anything irrigated and green at harvest time is a barrier, not fuel -- our
# June 2026 imagery showed two of our own fields behaving exactly like that.
CROP_NOTES = {
    "wheat":            "fuel -- the case we built and measured",
    "barley":           "fuel -- same season, same machines, same model",
    "oats / rye":       "fuel -- same as wheat",
    "lentils / chickpeas": "fuel when dry at harvest -- shorter, lighter fuel load",
    "sunflower":        "fuel late season -- stalks stay standing after seed harvest",
    "hay / dry pasture":"fuel -- cutting order of meadows works the same way",
    "potato / vegetables (irrigated)": "barrier -- green and wet at harvest; NOT fuel",
    "orchards / vines": "partial -- a mixed case; treat as barrier unless dry understorey",
}


# ---------------------------------------------------------------------------
# MAP HELPERS
# ---------------------------------------------------------------------------

def field_at(lat, lon, tolerance_m=25.0, fields=None):
    """Which field did the user tap? Point-in-polygon on the boundaries, with
    a small tolerance so a thumb landing just outside the edge still counts."""
    pool = fields if fields is not None else all_fields()
    p = Point(lon, lat)
    best, best_d = None, None
    for f in pool:
        if f.poly_ll.contains(p):
            return f.name
        d = f.poly_ll.exterior.distance(p) * 105_000     # degrees -> ~metres
        if d <= tolerance_m and (best_d is None or d < best_d):
            best, best_d = f.name, d
    return best


def fields_geojson(selected=(), harvested=(), today=None, rank=None, fields=None):
    """The fields as a GeoJSON FeatureCollection with a 'state' per feature."""
    pool = fields if fields is not None else all_fields()
    rank = rank or {}
    feats = []
    for f in pool:
        if f.name in set(harvested):
            state = "done"
        elif f.name == today:
            state = "today"
        elif f.name in set(selected):
            state = "mine"
        else:
            state = "other"
        feats.append({
            "type": "Feature",
            "properties": {"name": f.name, "area_ha": round(f.area_ha, 1),
                           "state": state, "rank": rank.get(f.name)},
            "geometry": {"type": "Polygon",
                         "coordinates": [list(map(list, f.poly_ll.exterior.coords))]},
        })
    return {"type": "FeatureCollection", "features": feats}


# ---------------------------------------------------------------------------
# EXPORTS
# ---------------------------------------------------------------------------

def whatsapp_text(rows, harvested=(), lang="en"):
    """The plan as a short message the cooperative leader forwards to the group."""
    t = tpl(lang)
    lines = [t["wa_title"]]
    if harvested:
        lines.append(t["wa_cut"].format(list=", ".join(harvested)))
    for r in rows:
        lines.append(t["wa_line"].format(day=r["Day"], f=r["Field"]))
    lines.append(t["wa_footer"])
    return "\n".join(lines)


def schedule_csv(rows):
    cols = ["Day", "Field", "Hectares", "Days", "Largest block before (ha)",
            "Largest block after (ha)", "Why this field now"]
    lines = [",".join(cols)]
    for r in rows:
        lines.append(",".join('"' + str(r[c]).replace('"', '""') + '"' for c in cols))
    return "\n".join(lines)


def calendar_html(rows, title=None, lang="en"):
    """A one-page printable calendar: the whole product for a village offline."""
    t = tpl(lang)
    title = title or t["cal_title"]
    h = t["cal_head"]
    body = "".join(
        f"<tr><td class='d'>{html.escape(str(r['Day']))}</td>"
        f"<td class='f'>{html.escape(str(r['Field']))}</td>"
        f"<td>{r['Hectares']} {t['ha']}</td>"
        f"<td>{r['Largest block after (ha)']} {t['ha']}</td>"
        f"<td class='why'>{html.escape(r['Why this field now'])}</td></tr>"
        for r in rows
    )
    return f"""<!doctype html><html lang="{lang}" dir="{t['dir']}"><head><meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>
 body{{font-family:Arial,'Segoe UI',Tahoma,sans-serif;margin:18mm;color:#222}}
 h1{{margin:0 0 4px}} .sub{{color:#666;margin:0 0 14px}}
 table{{border-collapse:collapse;width:100%;font-size:14px}}
 th{{text-align:start;font-size:11px;letter-spacing:.06em;text-transform:uppercase;
     color:#666;border-bottom:2px solid #ccc;padding:6px}}
 td{{padding:8px 6px;border-bottom:1px solid #e5e5e5;vertical-align:top}}
 td.d{{font-weight:bold;white-space:nowrap}}
 td.f{{font-weight:bold;font-size:20px;color:#8a5a00}}
 td.why{{color:#444}}
 @media print{{body{{margin:12mm}}}}
</style></head><body>
<h1>{html.escape(title)}</h1>
<p class="sub">{html.escape(t['cal_sub'])}</p>
<table><thead><tr>{''.join(f'<th>{html.escape(x)}</th>' for x in h)}</tr></thead>
<tbody>{body}</tbody></table>
</body></html>"""


# ---------------------------------------------------------------------------
# SELF-TEST: `python app_logic.py`
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    names = field_names()
    p = plan(names)
    print(f"plan on all {len(names)} fields: order {' -> '.join(p['order'])}")
    print(f"  optimal {p['optimal'].fire_risk_score:.1f} vs naive "
          f"{p['naive'].fire_risk_score:.1f}  ({p['pct_vs_naive']:+.1f}%)")
    for r in p["rows"][:2]:
        print(f"  day {r['Day']:<6} field {r['Field']:<4} -> {r['Why this field now']}")

    # Arabic: same order, same numbers, Arabic sentences
    pa = relabel(p, "ar")
    assert pa["order"] == p["order"] and pa["rows"][0]["Largest block after (ha)"] == \
        p["rows"][0]["Largest block after (ha)"]
    print("  arabic ->", pa["rows"][1]["Why this field now"])
    assert "حقل" in whatsapp_text(pa["rows"], lang="ar") and 'dir="rtl"' in calendar_html(pa["rows"], lang="ar")

    r = replan(p, harvested=["13", "nte"], position="nte")
    print(f"replan after 13 + nte cut: {' -> '.join(r['order'])}  "
          f"(remaining fire risk {r['remaining_fire_risk']:.1f})")

    # Edge cases a curious tester WILL hit
    done = replan(p, harvested=names, position="nte")
    assert done["done"] and done["rows"] == [] and done["order"] == []
    one = replan(p, harvested=names[:-1])
    assert not one["done"] and len(one["rows"]) == 1

    # A farm the farmer drew: three rough rectangles near Zahle
    def rect(lon, lat, w=0.003, h=0.002):
        return {"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[
            [lon, lat], [lon + w, lat], [lon + w, lat + h], [lon, lat + h], [lon, lat]]]}}
    drawn = [rect(35.90, 33.80), rect(35.9032, 33.80), rect(35.90, 33.8022),
             {"type": "Feature", "geometry": {"type": "Point", "coordinates": [35.9, 33.8]}}]
    custom = custom_fields_from_geojson(drawn)
    assert [f.name for f in custom] == ["1", "2", "3"], custom
    print(f"drawn farm: {len(custom)} fields, areas "
          + ", ".join(f"{f.area_ha:.1f} ha" for f in custom))
    pc = plan(field_names(custom), fields=custom, lang="ar")
    print(f"  plan for the drawn farm: {' -> '.join(pc['order'])} "
          f"({pc['pct_vs_naive']:+.1f}% vs naive)")
    assert field_at(33.801, 35.901, fields=custom) == "1"

    e = economics(p)
    print(f"economics: {e['total_ha']:.0f} ha at stake ≈ ${e['value_usd']:,.0f} "
          f"(assumed {e['yield_t_per_ha']} t/ha × ${e['price_usd_per_t']:.0f}/t); "
          f"farmer cost ${e['farmer_cost_usd']:.0f}")
    print("app_logic self-test OK")
